# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: freshEHR Clinical Informatics
email: info@freshehr.com
description: > # this means to ignore newlines until "baseurl:"
 Open standards based clinical informatics for modern health and care applications
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://freshehrteam.github.io/freshehr-website/" # the base hostname & protocol for your site
github_username:  freshehr

collections:
  - partners


# Build settings
markdown: kramdown
exclude: ["README.md"]
include: ['_pages']

